/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./Interfaces";
export type { interfaces };
import type * as swapTokenSol from "./SwapToken.sol";
export type { swapTokenSol };
